import "./globals.css";
import styles from "./layout.module.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NavBar } from "@/components/chrome/navbar";
import { Footer } from "@/components/chrome/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	// rome-ignore lint/correctness/noUndeclaredVariables: React 17+ JSX implicitly imports React
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={[inter.className, styles.container].join(" ")}>
				<nav className={styles.navbar}>
					<NavBar />
				</nav>
				<main className={styles.content}>{children}</main>
				<footer className={styles.footer}>
					<Footer />
				</footer>
			</body>
		</html>
	);
}
