import Grid from "@mui/material/Grid";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navigation from "./components/Navigation";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main>
        <Grid container spacing={3} justifyContent={"start"}>
          <Grid item xs></Grid>
          <Grid item xs={6}>
            Content
          </Grid>
          <Grid item xs></Grid>
        </Grid>
        {
          // menu
          // hero image
          // name
          // tagline
          // links
          // about
          // contact form
        }
      </main>

      <footer>©️ 2022 Stefan Hoth</footer>
    </div>
  );
};

export default Home;
